### ISSUE TITLE
Rosetta 2.0.0 release [for GFork]

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/rosetta#203]
```[tasklist]
### Tasks
- [x] Manual Construction API testing (on mycelo testnet)
- [x] Remove all GFork TODOs in kliento, rosetta
- [x] Update kliento's blockchain dependency to 1.8.0-stable
- [x] Update rosetta's blockchain & kliento dependencies to 1.8.0-stable & updated kliento version
- [x] go mod tidy for kliento & rosetta
- [x] Update rosetta docker image
- [x] Rosetta release notes, tag, updated version
- [x] Sanity checks on released tag version
- [x] Run CLI checks on released tag version (update deployed rosetta nodes)
- [x] run deployed rosetta nodes overnight (v2.0.0)
- [x] communicate with stakeholders, mark release as stable
```
